name: ccem
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - cudatoolkit=11.1.1
  - ffmpeg=4.2.2
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - intel-openmp=2022.1.0
  - jpeg=9b
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libidn2=2.3.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.1.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libvpx=1.7.0
  - libwebp=1.2.0
  - lz4-c=1.9.3
  - mkl=2022.1.0
  - ncurses=6.3
  - nettle=3.7.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - openh264=2.1.1
  - openssl=1.1.1s
  - pillow=9.2.0
  - pip=22.2.2
  - python=3.8.15
  - pytorch=1.9.1
  - readline=8.2
  - setuptools=65.5.0
  - sqlite=3.39.3
  - tk=8.6.12
  - torchvision=0.10.1
  - typing_extensions=4.3.0
  - wheel=0.37.1
  - x264=1!157.20191217
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.4.9
  - pip:
    - absl-py==1.3.0
    - antlr4-python3-runtime==4.9.3
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - click==8.1.3
    - cloudpickle==2.2.0
    - cython==0.29.32
    - decorator==4.4.2
    - dm-control==0.0.403778684
    - dm-env==1.5
    - dm-tree==0.1.7
    - docker-pycreds==0.4.0
    - fasteners==0.18
    - future==0.18.2
    - gitdb==4.0.9
    - gitpython==3.1.29
    - glfw==2.5.5
    - gym==0.21.0
    - h5py==3.7.0
    - idna==3.4
    - imageio==2.22.4
    - imageio-ffmpeg==0.4.7
    - labmaze==1.0.5
    - lxml==4.9.1
    - metaworld==0.1.0
    - moviepy==1.0.3
    - mujoco-py==2.1.2.14
    - numpy==1.23.4
    - omegaconf==2.2.3
    - opencv-python==4.6.0.66
    - pandas==1.5.1
    - patchelf==0.16.1.0
    - pathtools==0.1.2
    - plotly==5.13.0
    - proglog==0.1.10
    - promise==2.3
    - protobuf==4.21.9
    - psutil==5.9.4
    - pycparser==2.21
    - pyopengl==3.1.6
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.6
    - pyyaml==6.0
    - requests==2.28.1
    - scipy==1.9.3
    - sentry-sdk==1.11.0
    - setproctitle==1.3.2
    - shortuuid==1.0.11
    - six==1.16.0
    - smmap==5.0.0
    - tenacity==8.2.1
    - termcolor==2.1.0
    - tqdm==4.64.1
    - urllib3==1.26.12
    - wandb==0.13.5
